//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjABI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int IdentifiantContact { get; set; }
        public string NomContact { get; set; }
        public string PrenomContact { get; set; }
        public string Fonction { get; set; }
        public string TelephoneContact { get; set; }
        public string EmailContact { get; set; }
        public int IdClient { get; set; }
        public Nullable<int> Duree { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
